spring.application.name=weblearning

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PW}

spring.jpa.hibernate.ddl-auto=update

spring.liquibase.enabled=false

server.servlet.context-path=/api

jwt.secret=your-256-bit-secret-key-here-make-it-long
jwt.expiration=86400000

